data_source:
  type: csv
  path: sample_data.csv

features:
  moving_average: [market_price]
  price_momentum: [market_price, moving_average]
  sentiment_momentum: [sentiment_score]
  headline_sentiment: [headline]
  text_sentiment: [text_body]
  headline_sentiment_spread: [sentiment_score, headline_sentiment]
  text_sentiment_spread: [text_sentiment, headline_sentiment]

event_triggers:
  daily_1300:
    type: time
    trigger_time: ["13:00"]
    dependencies: [price, news_update]
  price:
    type: condition
    condition: "state['price'] > 1"
  news_update:
    type: condition
    condition: "state['has_new_news'])"

feature_store:
  type: lmdb
  config:
    path: ./tmp/feature_store
